services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: nodemon app/index.js
    ports:
      - "10000:10000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
