FROM node:18-slim

RUN apt-get update && apt-get install -y \
    wget gnupg unzip ca-certificates fonts-liberation libappindicator3-1 \
    libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 \
    libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 \
    libxdamage1 libxrandr2 libdrm2 libxshmfence1 libgbm1 libgtk-3-0 \
    xdg-utils --no-install-recommends && \
    rm -rf /var/lib/apt/lists/* && \
    wget https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux64/chrome-linux64.zip && \
    unzip chrome-linux64.zip && \
    mv chrome-linux64 /opt/chrome && \
    ln -s /opt/chrome/chrome /usr/bin/chromium

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /app

COPY package*.json ./
RUN npm install -g nodemon && npm install

COPY . .

EXPOSE 10000

CMD ["nodemon", "app/index.js"]